name: Berrybenka
on:
  schedule:
    - cron: "30 20 * * *" # at 3.30 UTC+7
  workflow_dispatch:

jobs:
  scraping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: berrybenka

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scraping process
        run: |
          scrapy crawl berrybenka -o data/berrybenka.json

      - name: File checking
        run: |
          jq "map(select(.name)) | length" data/berrybenka.json
        
      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          timestamp=$(TZ='Asia/Jakarta' date +'%F %H:%M %Z')
          chmod +x rename.sh
          cd data
          bash ../rename.sh
          git add *.json
          git commit -m "Update data from ${{ github.ref_name }} on ${timestamp}" || exit 0
          git push
