name: Gaudi
on:
  #schedule:
  #  - cron: "30 20 * * *" # at 3.30 UTC+7
  workflow_dispatch:

jobs:
  scraping-job:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scraping process
        run: |
          scrapy crawl gaudi -L WARNING -o data/gaudi.csv
          wc -l data/gaudi.csv
