name: "Puru Kambera"
on:
  schedule:
    - cron: "30 20 * * *" # at 3.30 UTC+7
  workflow_dispatch:

jobs:
  scraping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: purukambera

      - name: Clone Shopify
        uses: actions/checkout@v3
        with:
          repository: akherlan/shopify
          path: shopify
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r shopify/requirements.txt

      - name: Crawling process
        run: |
          python shopify.py -c crawl -i https://purukambera.com purukambera.txt
        
      - name: Scraping process
        run: python shopify.py -c scrape -i purukambera.txt data/purukambera.json

      - name: File checking
        run: |
          wc -l purukambera.txt
          jq "map(select(.title)) | length" data/purukambera.json
        
      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          timestamp=$(TZ='Asia/Jakarta' date +'%F %H:%M %Z')
          chmod +x rename.sh
          cd data
          bash ../rename.sh
          git add *.json
          git commit -m "Update data from ${{ github.ref_name }} on ${timestamp}" || exit 0
          git push
